; This is a mxdev configuration file
; it can be used to override versions of packages already defined in the
; constraints files and to add new packages from VCS like git.
; to learn more about mxdev visit https://pypi.org/project/mxdev/

[settings]
main-package = -e .[test]
ignores =
    plone.restapi

plone = https://github.com/plone
plone_push = git@github.com:plone

[plone.base]
url = ${settings:plone}/plone.base.git
pushurl = ${settings:plone_push}/plone.base.git
branch = plip-recyclebin-interface

[Products.CMFPlone]
url = ${settings:plone}/Products.CMFPlone.git
pushurl = ${settings:plone_push}/Products.CMFPlone.git
; branch = rohnsha0-plip-recyclebin-patch
branch = cekk_recycle_bin_fixes
