- Improved blocks transformers: now we can handle generic transformers [cekk]
- Add generic block transformer for handle resolveuid in all blocks that have a *url* or *href* field [cekk]
- Add "smart fields" concept: if block has a *searchableText* field, this will be indexed in Plone [cekk, tiberiuichim]
